### ISSUE TITLE
Filling missing data

### ISSUE THREAD

**Issue by jddingemanse** [jddingemanse/awtiCodeDev#8]
Automizing different filling missing data techniques.

**Comment by jddingemanse** [comment]
@IsraelGebresilassie , you have uploaded the code file with an example of three filling missing data techniques ([Estimation of Missing Data.py](https://github.com/jddingemanse/awtiCodeDev/blob/904e7fa0548bf6b1ad8546262e5d634ed0c72639/code/Estimation%20of%20Missing%20%20Data.py)). When I run the example code of the Inverse distance method (IDW), I get, for example, for `Parb` values of 0.35-1.00. If I understand it correctly, these values should be used to fill missing data for the Arba Minch column.

**Possible wrong IDW calculation**
Can you double check the mathematics of IDW and how they are implemented in the code, because I think the values should be higher. At this moment, for example, based on Mirab (8.0), Chano (10) and Shara (9), together with distances to Arba Minch of 10, 12 and 14, respectively, gives an estimation of 0.767. That would seem incorrect.

**Comment by IsraelGebresilassie** [comment]
Ok, I will check.

*With Regards, *

*************************************************

*Israel Gebresilasie (MSc in Climate Change and Development)*


*Lecturer, Faculty of Meteorology and Hydrology, Water Technology
Institute, Arba Minch University*



*Arba Minch Ethiopia ******************************* Phone: +251 927833912*

*Alternate email: ***@***.***
***@***.***>*

**Comment by IsraelGebresilassie** [comment]
here is the calculation 
(8/10^2)+(10/12^2)+(9/14^2)  for numerator = 0.195   approximately
(1/10+1/12+1/14)                     for Dominator = 0.255    approximately
then 0.195/0.255= 0.765    approximately

**Comment by jddingemanse** [comment]
> here is the calculation (8/10^2)+(10/12^2)+(9/14^2) for numerator = 0.195 approximately (1/10+1/12+1/14) for Dominator = 0.255 approximately then 0.195/0.255= 0.765 approximately

Good that you checked. But now about the implication; it feels incorrect that values 8, 9 and 10 result in an estimated 0.765. It should be somewhere between 8 and 10, with the station closest to Arba Minch having the most weight in the eventual outcome.

Is the 0.765 maybe a step in between, that is needed to calculate the final actual precipitation estimation?
- Can you share the full equations such as you also showed in your slides?

**Comment by IsraelGebresilassie** [comment]
Thank you Jan for your interesting suggestion based on the real interpretations but  before applying the change we have to discuses. her is my formula  and let me check it again.  

![image](https://user-images.githubusercontent.com/106670155/210130793-cc65cac3-7c47-49a2-a058-f082f20b379b.png)

**Comment by jddingemanse** [comment]
> Thank you Jan for your interesting suggestion based on the real interpretations but before applying the change we have to discuses. her is my formula and let me check it again.
> 
> ![image](https://user-images.githubusercontent.com/106670155/210130793-cc65cac3-7c47-49a2-a058-f082f20b379b.png)

Ah, if that is the formula, then, of the following ...

> (8/10^2)+(10/12^2)+(9/14^2) for numerator = 0.195 approximately
> (1/10+1/12+1/14) for Dominator = 0.255 approximately
the calculation of the denominator is incorrect. It should be instead:
- 1/(10^2) + 1/(12^2) + 1/(14^2) = 0.015
Also, recalculating the numerator leads to 0.126
![image](https://user-images.githubusercontent.com/86903675/210135794-9bf5d1b7-d998-4a36-9141-2e86a6c5baa9.png)
So final answer would be 0.126/0.015=8.4. That answer sounds quite reasonable.

Then, I propose the following code:
```
Parb=(Data.Mirab.replace(np.nan,0)/(DAM**2)+Data.Chano.replace(np.nan,0)/(DAC**2)+Data.Shara.replace(np.nan,0)/(DAS**2))/(1/(DAM**2)+1/(DAC**2)+1/(DAS**2))
Pmirab=( Data.Arbaminch.replace(np.nan,0)/(DAM**2)+Data.Chano.replace(np.nan,0)/(DCM**2)+Data.Shara.replace(np.nan,0)/(DMS**2))/(1/(DAM**2)+1/(DCM**2)+1/(DMS**2))
PCHANO=( Data.Arbaminch.replace(np.nan,0)/(DAC**2)+Data.Mirab.replace(np.nan,0)/(DCM**2)+Data.Shara.replace(np.nan,0)/(DCS**2))/(1/(DAC**2)+1/(DCM**2)+1/(DCS**2))
PSHARA=(Data.Arbaminch.replace(np.nan,0)/(DAS**2)+Data.Mirab.replace(np.nan,0)/(DMS**2)+Data.Chano.replace(np.nan,0)/(DCS**2))/(1/(DAS**2)+1/(DMS**2)+1/(DCS**2))
```

**Comment by IsraelGebresilassie** [comment]
Thank you so much, Jan but in your calculation, I think there is typing error for the numerator and you are correct for the denominator I forgot the power of two (squaring). 
![image](https://user-images.githubusercontent.com/106670155/210152438-e63747bc-cb0c-41cc-ac76-683d518d2fd1.png)
  for the rest ok for me 
thank you again for your correction. keep going.....

**Comment by IsraelGebresilassie** [comment]
Thank you so much, Jan but in your calculation, I think there is typing error for the numerator and you are correct for the denominator I forgot the power of two (squaring). 
![image](https://user-images.githubusercontent.com/106670155/210152438-e63747bc-cb0c-41cc-ac76-683d518d2fd1.png)
  for the rest ok for me 
thank you again for your correction. keep going.....

**Comment by jddingemanse** [comment]
> Thank you so much, Jan but in your calculation, I think there is typing error for the numerator and you are correct for the denominator I forgot the power of two (squaring). ![image](https://user-images.githubusercontent.com/106670155/210152438-e63747bc-cb0c-41cc-ac76-683d518d2fd1.png) for the rest ok for me thank you again for your correction. keep going.....

Indeed, I made a mistake, even for some reason in both the numerator and the denominator. To fully say it correctly:
- 8/(10**2)+10/(12**2)+9/(14**2) = 0.195
- 1/(10**2)+1/(12**2)+1/(14**2) = 0.022
- 0.195/0.022 = 8.86

After you have changed your code file, I will close this issue. Any other items related to filling missing data we can do under a discussion, or we can create a new and more specific issue for that.

**Comment by IsraelGebresilassie** [comment]
Now the code is modified.

**Comment by jddingemanse** [comment]
Perfect; I hereby close the issue. If there is any remark regarding filling missing data code, please start a discussion, or open a new issue.
